version: "2"
services:
  app:
    container_name: frontend
    restart: always
    image: dev.cewit.stonybrook.edu:7443/pensive/website:latest
    volumes:
      - ".:/src"
      - /src/node_modules
    ports:
      - "3000:3000"